### ISSUE TITLE
Maximale Anzahl an Anhängen nur 30 (Bilder)?

### ISSUE THREAD

**Issue by SpartanerODS** [theZiz/ods-upgrade#23]
Robtrek [berichtet in #9](https://www.outdoorseiten.net/vb5/forum/ods-gemeinschaft/hilfe-verbesserungsvorschl%C3%A4ge-kritik/forum-aa/3005872-neues-forum-fotos-verschwinden-unerw%C3%BCnschte-anh%C3%A4nge?p=3006390#post3006390): "Maximale Anzahl an Anhängen erreicht. Pro Beitrag sind maximal 30 Anhänge erlaubt."
Kann man das höher setzen? Sonst muss man eventuell noch Tage teilen in prall bebilderten Reiseberichten. Aber 100 müssten schon ausreichen. Wäre alles kein Problem, hätte man die alte Galerie noch.

**Comment by Pfad-Finder** [comment]
Robtrek fragt noch mal (https://www.outdoorseiten.net/vb5/forum/ods-gemeinschaft/hilfe-verbesserungsvorschl%C3%A4ge-kritik/forum-aa/3004482-neues-forum-fragen-und-anregungen-an-den-maschinenraum?p=3009883#post3009883):

"Ich habe jetzt einen Reisebericht mit Fotos veröffentlicht, anscheinend erfolgreich. (...) Es wäre hilfreich, wenn die Website-Admin nochmal klarstellen könnte, ob diese 30 Bilder Grenze tatsächlich gilt oder nur eine Legende ist. "

Würde mich auch interessieren, damit ich das Wording im geplanten FAQ entsprechend gestalten kann.

**Comment by theZiz** [comment]
30 ist korrekt.
![grafik](https://user-images.githubusercontent.com/385145/103699887-e8dd1a80-4fa3-11eb-8da1-816f16dd482e.png)
Könnte ich übrigens bei Bedarf auch einfach hochsetzen. Auf 100 oder so. Mir ist das Wumpe... :grin:

**Comment by theZiz** [comment]
Ach Kinners, wozu bin ich Admin... Anzahl ist auf 100 hochgesetzt. ZACK und Zu. :grinning:
