### ISSUE TITLE
Foren als gelesen markieren prominenter platzieren 

### ISSUE THREAD

**Issue by theZiz** [theZiz/ods-upgrade#29]
Das "Foren als gelesen markieren", das sich recht weit unten auf der Foren-Übersichtsseite versteckt, würde ich mir ebenfalls oben in der Menüleiste wünschen, denn das ist nach dem Durchgehen der "Neue Themen" der Standardlink, den ich klicke, bevor ich das Forum verlasse, damit ich beim nächsten Besuch nur angezeigt bekomme, was seit meinem letzten Besuch neu ist. Im alten Forum war das glaube ich auch möglich, da musste ich nicht erst auf die Übersichtsseite, scrollen und nochmal klicken.

**Comment by bambus-58** [comment]
Vorschlag: <Forum als gelesen markieren> soll erst erscheinen, wenn der Button "Neue Beiträge" (Danke für die schnelle Implementierung!) angewählt wurde, plaziert neben den Suchfeldern (Schlüsselwörter/Benutzer/Stichworter  /**--> Alles als gelesen markieren**). Mit Drücken des Buttons soll die Suche nach neuen Beiträgen erneut ausgeführt werden.
--> Wie bei der alten Forensoftware.

**Comment by theZiz** [comment]
Habs unten eingefügt:

![grafik](https://user-images.githubusercontent.com/385145/103172791-4233a400-4856-11eb-8af5-768ec8f5bea5.png)

**Comment by bambus-58** [comment]
Vielen Dank, genau so hab, zumindest ich, es mir vorgestellt.
