### ISSUE TITLE
Unter Chrome werden externe Bilder im ODS-Reisebericht nicht angezeigt

### ISSUE THREAD

**Issue by SpartanerODS** [theZiz/ods-upgrade#33]
[Beispiel siehe #258](https://www.outdoorseiten.net/vb5/forum/ods-gemeinschaft/hilfe-verbesserungsvorschl%C3%A4ge-kritik/forum-aa/3004482-neues-forum-fragen-und-anregungen-an-den-maschinenraum?p=3007900#post3007900). 
Wenn es nur am "unsicher" liegen sollte, wieso werden die Bilder dann in Chrome dennoch angezeigt, wenn man die Bildadresse direkt in Chrome aufruft (ohne Umweg über ODS)? Die Bilder sind also da, dann muss der Fehler doch eher an ODS liegen, oder?

In allen anderen probierten Browsern werden die Bilder im Reisebericht problemlos angezeigt (Mi-Browser Android, Mac Safari, Win10 Edge). 

Dazu kommt, wenn das Bild im neuen Forum neu eingefügt wird, dann funktioniert es auch unter Chrome problemlos mir diesem Link: 

[ATTACH=JSON]{"alt":"Klicke auf die Grafik f\u00fcr eine vergr\u00f6\u00dferte Ansicht Name: 1_2.jpg Ansichten: 0 Gr\u00f6\u00dfe: 43,8 KB ID: 3007901","data-align":"none","data-attachmentid":"3007901","data-size":"full","title":"1_2.jpg"}[/ATTACH]

**Comment by theZiz** [comment]
> Beispiel siehe #258.
Wenn es nur am "unsicher" liegen sollte, wieso werden die Bilder dann in Chrome dennoch angezeigt, wenn man die Bildadresse direkt in Chrome aufruft (ohne Umweg über ODS)? Die Bilder sind also da, dann muss der Fehler doch eher an ODS liegen, oder?

Nein. Chrome will dich schützen und verhindert das Anzeigen von unsicherem Content in sicherem Content. Die "Schuld" liegt beim Ersteller, der einen `http` Link statt eines `https` Links verwendet.

> In allen anderen probierten Browsern werden die Bilder im Reisebericht problemlos angezeigt (Mi-Browser Android, Mac Safari, Win10 Edge).

Ja, Google weiß halt, was gut für dich ist. ;)

> Dazu kommt, wenn das Bild im neuen Forum neu eingefügt wird, dann funktioniert es auch unter Chrome problemlos mir diesem Link:
> [ATTACH=JSON]{"alt":"Klicke auf die Grafik f\u00fcr eine vergr\u00f6\u00dferte Ansicht Name: 1_2.jpg Ansichten: 0 Gr\u00f6\u00dfe: 43,8 KB ID: 3007901","data-align":"none","data-attachmentid":"3007901","data-size":"full","title":"1_2.jpg"}[/ATTACH]

Genau, weil dann ist es kein unsicherer Content in sicherem Content, sondern einfach "nur" unsicherer Content. ;)
