### ISSUE TITLE
Fundort "meine neuesten Beiträge"

### ISSUE THREAD

**Issue by lina-ods** [theZiz/ods-upgrade#36]
"meine neuesten Beiträge" findet man derzeit nicht unter diesem Menüpunkt (Unterpunkt des Menüpunkts "username"), sondern nach Anklicken von "Mein Profil" (Unterpunkt des Menüpunkts "username") in einer Liste unter dem Texteingabefenster.

**Comment by theZiz** [comment]
Denke, das ist das gleiche wie https://github.com/theZiz/ods-upgrade/issues/11
