### ISSUE TITLE
GPX-Anhänge größer als 1,9 MB

### ISSUE THREAD

**Issue by DerWafer** [theZiz/ods-upgrade#43]
Laut einem Test von Spartaner sind GPX-Anhänge nur bis zu einer Größe von 1,9 MB möglich. Wer lange Touren mit Waypoints und Namen macht, der kann da schon mal drüber kommen. Solange es von der Performance der Anzeige her noch Sinn macht wären größere Dateien wünschenswert.

**Comment by theZiz** [comment]
Done, nun gehen 19,07 MiB ;)
