### ISSUE TITLE
Sonderzeichen werden als ? angezeigt

### ISSUE THREAD

**Issue by DerWafer** [theZiz/ods-upgrade#46]
Ich verwende z.B. Pfeile um die Höhenmeter an zu geben, die ich bei einer Tour rauf oder runter bin. Solche Sonderzeichen sind im Editor eingebbar und werden direkt nach dem Speichern des Beitrages auch angezeigt. Aber nach einem Neuladen der Seite sind die Zeichen dann durch ein Fragezeichen ersetzt. Beim Zitieren oder Editieren tauchen die Sonderzeichen dann wieder auf. Das gilt für viele Zeichen: Kyrilische Buchstagen ebenso wie die in Skandinavien üblichen Zeichen.

**Comment by theZiz** [comment]
Done, siehe: https://github.com/theZiz/ods-upgrade/issues/9
