### ISSUE TITLE
Farbige Hinterlegung zur Markierung des jeweils ersten Threadpostings 

### ISSUE THREAD

**Issue by lina-ods** [theZiz/ods-upgrade#57]
ist eigentlich völlig sinnlos, d.h. bietet keinerlei Mehrwert. 
Der Farbton konkurriert außerdem mit den im Posting vorhandenen Fotos sowie mit der farbigen Hinterlegung der User-Spalte links.

**Comment by theZiz** [comment]
Okay, okay, okay... Damit das Thema endlich vom Tisch ist, mach ich es aus. :stuck_out_tongue_winking_eye:
