### ISSUE TITLE
Performance beim Sichern verbessern

### ISSUE THREAD

**Issue by DerWafer** [theZiz/ods-upgrade#62]
Beim Sichern dauert es extrem lange bis man weiter machen kann.

**Comment by theZiz** [comment]
Ist das das gleiche wie https://github.com/theZiz/ods-upgrade/issues/37 ? Also passiert das auch nur beim Bearbeiten?

**Comment by DerWafer** [comment]
Ja, das ist das gleiche. Ich hatte nicht nochmal alles durchgelesen. Und die standardworte "Performance" oder "Speichern" bzw. "sichern" war nirgends zu finden.

**Comment by lina-ods** [comment]
Ja, es dauert lange, sowohl beim Sichern als auch beim Bearbeiten.
