### ISSUE TITLE
Rechtschreibfehler bei Zugriff ohne Berechtigung

### ISSUE THREAD

**Issue by DerWafer** [theZiz/ods-upgrade#64]
Wenn man auf eine Seite zugreift, auf die man keine Berechtigung hat, ist ein Rechtschreibfehler:

"Entschuldige, Du bist nicht autorisiert diese Seite zu sehen. Für Hilfe wende Dich an den **Sieten**-Administrator."

Zu sehen z.B. Hier:  https://www.outdoorseiten.net/vb5/node/3008815

**Comment by theZiz** [comment]
Fiel mir schon länger auf, hat mich aber nie genug gestört. :grin:
