### ISSUE TITLE
Beitrag/Thema wird trotz Fehlermeldung angelegt

### ISSUE THREAD

**Issue by Pfad-Finder** [theZiz/ods-upgrade#66]
Beim Anlegen des Reiseberichts "Die Reise durch Ukrillisch-Polen" habe ich beim Speichern eine Fehlermeldung erhalten (irgendwas mit Line 1 in Column 1, habe ich natürlich nicht notiert). Daraufhin habe ich Vorschaumodus genutzt (alles prima) und noch mal auf Speichern geklickt. Dann habe zufällig im anderen Fenster gesehen, dass das Thema tadellos angelegt worden ist, aber zwei Mal (wahrscheinlich, weil ich zwei Mal auf Speichern gedrückt habe). Nach meinem Verständnis sollte der User eine Fehlermeldung nur dann sehen, wenn tatsächlich etwas nicht funktioniert.

**Comment by theZiz** [comment]
Sollte das gleiche Problem wie https://github.com/theZiz/ods-upgrade/issues/59 sein
