### ISSUE TITLE
Fehler beim Speichern von neuen Beiträgen im Quelltext Modus: "200 parsererror SyntaxError:..."

### ISSUE THREAD

**Issue by Robtrek** [theZiz/ods-upgrade#68]
Fehlermeldung beim Veröffentlichen eines Beitrags: 

**Fehler beim Speichern des Inhalts: %1$s
Fehlerinformation: " 200 parsererror SyntaxError: Unexpected token F in JSON at position 0"**

Beschreibung: 
1. Der Text des Beitrags (17.900 Zeichen) wurde aus externer Textdatei in den Quelltext-Editor kopiert
2. Als Anhänge wurden 60 Fotos hochgeladen und in den Text eingefügt. Nach dem Einfügen hat jedes Foto im Quelltext einen Code wie diesen:  [ATTACH=CONFIG]temp_12453_1609593495225_16[/ATTACH]
3. In der Vorschau sieht alles perfekt aus, Text inkl. Sonderzeichen und Bilder.
4. Beim Veröffentlichen des Beitrags kommt o.g. Fehlermeldung. Die Fehlermeldung kommt auch, wenn man die Sonderzeichen aus dem Text entfernt und dann erneut versucht zu veröffentlichen. 
5. Während des ganzen Prozesses wurde er WYSIWYG-Editor nicht eingeschaltet
6. Im Unterschied zum Issue #66 wird der Beitrag nicht angelegt. Der Fehler verhindert also die Veröffentlichung eines Reiseberichts.
7. EDIT - Folgende Schritte führten schließlich zum Erfolg, der Beitrag konnte jetzt veröffentlicht werden:
8. Ich hatte bisher versucht, den Beitrag in Chrome (auf PC) zu veröffentlichen, was immer wieder zu o.g. Fehlermeldung führte. Ich blieb auf Chrome in ODS eingeloggt, öffnete gleichzeitig Firefox und loggte mich dort auch in ODS ein.
9. Nun kopierte ich den Quelltext meines Beitrags inkl. der o.g. Foto-Codes von Chrome nach Firefox. In Firefox ließ sich der Beitrag dann veröffentlichen.
10. Ich musste in Firefox die Fotos nicht erneut hochladen.
11. EDIT - In diesem Issue geht es um die Fehlermeldung beim Veröffentlichen des Beitrags. Diese Fehlermeldung habe ich wie beschrieben umgangen. Nun ist leider ein neues Problem aufgetreten: die Fotos im Beitrag sind nur für mich sichtbar, für andere User nicht. Siehe Issue #70.
12.  EDIT - Eine mögliche Ursache für die o.g. Fehlermeldung ist, dass der Titel des Beitrags zu lang ist. Der Titel soll weniger als 80 Zeichen haben. Bitte zunächst den Titel kürzen und schauen, ob die Fehlermeldung damit beseitigt wird. Das hat in mehreren Fällen funktioniert.

**Comment by Pfad-Finder** [comment]
Hallo Robtrek,
ich muss Dich leider enttäuschen: Ich sehe als angemeldeter User (Win 8.1/Firefox) kein einziges Bild. In Issue #69 hatte ich mit einem ähnlichen Problem zu kämpfen. Es macht anscheinend auch einen Unterschied, ob man Ersteller der Fotos ist oder ein anderer User (angemeldet/nicht angemeldet).

**Comment by eduardszoecs** [comment]
Ich kann leider auch keine Bilder sehen :(  (Chromium Version 87.0.4280.66 (Official Build) Arch Linux (64-bit)).

Img-tags sind da:

```
<img data-tempid="temp_12456_1609593507846_748" data-size="full" border="0" src="filedata/fetch?filedataid=12456" alt="" data-fullsize-url="filedata/fetch?filedataid=12456" data-thumb-url="filedata/fetch?filedataid=12456" data-title="Klicke auf das Bild um die Originalversion zu sehen." data-caption="" class="bbcode-attachment js-need-data-att-update js-lightbox-participant">
```

Allerdings erhalte ich einen 404 ("Ungültige Datei angegeben") beim request:

https://www.outdoorseiten.net/vb5/filedata/fetch?filedataid=12456

Vielleicht ein Pfad problem? Oder die Bilder wurden nicht angelegt (weil zu viele im Post?)?

Im Eingangspost sehe ich dir Bilder, der tag und die URL sind aber anders:

```
<img src="https://www.outdoorseiten.net/fotos/data/500/medium/19Put055_resize.jpg" border="0">
```

Funktioniert auch hier:
<img src="https://www.outdoorseiten.net/fotos/data/500/medium/19Put055_resize.jpg" border="0">

**Comment by Pfad-Finder** [comment]
Hallo Edild,
der andere Pfad im Eingangspost rührt daher, dass der Beitrag noch in der alten Software mit eigenständiger Galerie erstellt worden ist.

**Comment by theZiz** [comment]
Also das Problem ist das selbe wie https://github.com/theZiz/ods-upgrade/issues/59, auch wenn du im Detail leicht andere Schritte gemacht hast.

Das mit den Bildern hat folgende Bewandnis:

Wenn du Bilder hochlädst, kommen die an einen temporären Ort. Würdest du während des Erstellen des Beitrags mal in einem anderen Tab nach deinen eingefügten Bildern in den Medien gucken, solltest du sie nicht sehen.
Erst wenn der Beitrag endgültig erstellt wird, werden die Bilder vom temporären Ort zu den Anhängen geschoben. Wenn der Beitrag nicht erstellt wird, werden die temporären Bilder irgendwann gelöscht. Das ist passiert.

Im Quelltext kann man das sogar sehen! Im Nicht-WYSIWYG-Modus sieht das erst so aus:
```
[ATTACH=JSON]{"data-align":"none","data-size":"large","data-tempid":"temp_12590_1609687087768_683"}[/ATTACH]
```

Nach dem Erstellen wird das zu
```
[ATTACH=JSON]{"alt":"Klicke auf die Grafik f\u00fcr eine vergr\u00f6\u00dferte Ansicht  Name: Mulde_097.jpg Ansichten: 0 Gr\u00f6\u00dfe: 1,09 MB ID: 3009567","data-align":"none","data-attachmentid":"3009567","data-size":"large"}[/ATTACH]
```
Er hat es eine `"data-tempid"`, später eine `"data-attachmentid"`.

Also bleibt dir leider nur ein Reupload.
