### ISSUE TITLE
Bilder verschwinden

### ISSUE THREAD

**Issue by Pfad-Finder** [theZiz/ods-upgrade#69]
Ich habe meinen Bieszczady-Reisebericht in der "Spielwiese" geschrieben (https://www.outdoorseiten.net/vb5/forum/ods-gemeinschaft/lagerfeuer/spielwiese-f%C3%BCr-forumsfrischlinge/17191-test-thread-f%C3%BCr-alle-m%C3%B6glichen-versuche/page17?16639-Test-Thread-f%FCr-alle-m%F6glichen-Versuche=&viewfull=1#post1101133) und dann ins Reiseberichts-Unterforum kopiert (https://www.outdoorseiten.net/vb5/forum/tourenberichte/tourenberichte-europa/3009302-pl-die-reise-nach-ukrillisch-polen). Ein Teil der Bilder legt auf meinem privaten Webspace, einen Teil habe ich aus Bequemlichkeitsgründen später auf dem ODS-Server angelegt.

Das Problem mit den Bildern auf dem ODS-Server scheint nun zu sein, dass man sie nicht aus der Spielwiese (nur angemeldet zu sehen) nicht uneingeschränkt in den öffentlichen Bereich übernehmen kann, jedenfalls werden sie nicht verlässlich angezeigt. Eine klare Regel kann ich nicht erkennen, ich vermute jedoch nach verschiedenen Versuchen, dass die Zugriffsregeln "Nur für angemeldete User" vs "öffentlich" auch für die Bilder gelten und daher die im nicht-öffentlichen Bereich abgespeicherten Bilder im öffentlichen Bereich nicht angezeigt werden. Die alte Lösung mit unabhängiger Galerie war da natürlich robuster, wenn auch vom Privatsphären-Schutz her bedenklicher.

**Comment by Robtrek** [comment]
Ich kann die Bilder in deinem o.g. Beitrag in Chrome-Windows, Firefox und Edge anschauen, wenn unsichere Inhalte erlaubt werden. Bei Firefox und Edge war das automatisch der Fall (inkl. einer Warnung, dass die Verbindung mit outdoorseiten.net nicht sicher ist). Bei Chrome-Windows musste ich zuerst manuell in den Website-Einstellungen unsichere Inhalte für outdoorseiten.net erlauben, dann konnte ich die Bilder sehen. Bei Chrome-Android ist mir dies nicht gelungen und ich konnte auf dem Smartfone nur deinen Text ohne Bilder sehen.

**Comment by theZiz** [comment]
Uff, ihr macht Dinge...
![grafik](https://user-images.githubusercontent.com/385145/103482661-5c372e80-4de2-11eb-9f3a-6e7e6eed768e.png)

Also zum Problem... Anhänge sind an Beiträge gebunden und auch an dessen Rechte. Das bedeutet zwei Dinge:

- Lösch den Beitrag auf der Spielwiese und deine Bilder sind weg.
- Nur wer die Rechte hat, die Spielwiese zu sehen, kann auch deine Bilder sehen.

Das Board hat echt böse bugs, aber ihr setzt dem ganzen noch die Krone auf. :sweat_smile:

**Comment by theZiz** [comment]
Achso, bevor ich hier dichtmache, noch eine Anmerkung zu deinem absolut richtigem Kommentar, dass die neue Lösung nicht sehr robust ist: Ich denke, wir werden auf eine neue Galerie umstellen müssen auf kurze Sicht.
