### ISSUE TITLE
Andere User sehen Bilder im Beitrag nicht. Autor sieht die eigenen Bilder nur, wenn eingeloggt.

### ISSUE THREAD

**Issue by Robtrek** [theZiz/ods-upgrade#70]
Dieser Post folgt auf Issue #68 und erweitert Issue #69. Überprüft werden kann das Verschwinden der Bilder **[an diesem ods-Post](https://www.outdoorseiten.net/vb5/forum/tourenberichte/tourenberichte-ferne-länder-übersee/113452-ru-rückkehr-aufs-putorana-plateau-ein-wildnisabenteuer?p=3009339#post3009339)**

Das Problem wurde in mehreren Browsern überprüft. Das Zulassen unsicherer Inhalte im Browser beseitigt das Problem nicht.

Problembeschreibung:
Ich veröffentlichte einen Beitrag mit 60 Bildern (hochgeladen als "Anhang") wie in Issue #68 beschrieben. Solange ich in ods eingeloggt bin, wird mir mein Beitrag korrekt angezeigt (Text mit allen Bildern). Wenn ich auslogge (und den Browser-Cache lösche), wird anschließend nur noch der Text angezeigt, die Bilder nicht mehr. Das Problem wurde für Chrome-Windows, Firefox-Windows und Chrome-Android überprüft. Es spielt keine Rolle, ob ich in Chrome-Windows unsichere Inhalte für www.outdoorseiten.net zulasse. Die Bilder in meinem eigenen Beitrag werden mir trotzdem erst angezeigt, wenn ich mich einlogge. Andere User sehen von meinem Beitrag immer nur den Text und nie die Bilder, auch wenn sie eingeloggt sind.
Das beschriebene Problem besteht nicht für Beiträge, die vor der Umstellung auf die neue Forumssoftware erstellt wurden. Im gleichen o.g. Thread werden ältere Beiträge immer korrekt mit allen Bildern angezeigt. Ein-/Ausloggen spielt dabei keine Rolle.
Rein spekulativ, was prinzipiell die **[Fehlerursache sein könnte](https://www.outdoorseiten.net/vb5/forum/ods-gemeinschaft/hilfe-verbesserungsvorschläge-kritik/forum-aa/3004482-neues-forum-fragen-und-anregungen-an-den-maschinenraum?p=3009459#post3009459)**.

Dieses Problem unterscheidet sich von dem in Issue #69, auch wenn die Symptome sich ähneln. Die Bilder im **[Beitrag des Users](https://www.outdoorseiten.net/vb5/forum/tourenberichte/tourenberichte-europa/3009302-pl-die-reise-nach-ukrillisch-polen)** aus Issue #69 werden mir immer genau dann angezeigt, wenn ich im Browser unsichere Inhalte erlaube. Ein-/Ausloggen spielt keine Rolle. Auch das wurde in mehreren Browsern überprüft.

**Comment by theZiz** [comment]
Ich denke, ich hab den Fehler in den beiden verlinkten Issues herleiten können. Leider wahrscheinlich ein Bedienungsproblem. Das ist nicht als Vorwurf gemeint, die Bedienung ist nicht sehr intuitiv. Aber dran ändern kann ich hier wahrscheinlich nichts (außer halt ne richtige Galerie einbauen).

Ich mach das hier also als Duplicate zu, wenn du anderer Meinung bist, dass ich was übersehen habe, gib Bescheid.
