### ISSUE TITLE
PN-Text in Benachrichtigungs-Email unvollständig

### ISSUE THREAD

**Issue by lina-ods** [theZiz/ods-upgrade#73]
Nach der ersten Zeile bricht die Nachricht ab, d.h. wenn man die gesamte PN lesen möchte, muss man sich einloggen. Das ist sehr unkomfortabel.

**Comment by theZiz** [comment]
Leider nicht änderbar: https://forum.vbulletin.com/forum/vbulletin-5-connect/vbulletin-5-connect-questions-problems-troubleshooting/vbulletin-5-support-issues-questions/4396783-email-notifications-are-far-too-short-how-can-i-make-them-longer
