### ISSUE TITLE
Suche und Biete

### ISSUE THREAD

**Issue by Fjaellraev** [theZiz/ods-upgrade#75]
Zur Zeit können Suche&Biete Topics auch direkt im Oberforum Kleinanzeigen erstellt werden.
Das natürlich auch schon ohne genügend andere Beiträge.
https://www.outdoorseiten.net/vb5/forum/ods-gemeinschaft/kleinanzeigen
https://www.outdoorseiten.net/vb5/forum/ods-gemeinschaft/kleinanzeigen/3009881-ski-langlaufschuhe
Ist sicher nicht Sinn der Sache...
Wie sieht es mit der Beitragsgrenze im direkten Suche&Biete Bereich aus?
Bis jetzt scheint es ja noch kein Problem zu sein, ist aber sicher nur eine Frage der Zeit.

**Comment by theZiz** [comment]
Guter Punkt, habs gefixt.
