### ISSUE TITLE
Beiträge von ignorierten Benutzern nicht ganz ausblenden

### ISSUE THREAD

**Issue by newHeiko** [theZiz/ods-upgrade#84]
Moin allerseits,

im neuen Forum werden Beiträge von ignorierten Nutzern gar nicht anzeigt. Hat mich einige Male verwirrt, weil in der Beitragsübersicht neue Beiträge zu einem Thema anzeigt werden, dann beim Klick darauf aber nicht...

Im alten Forum tauchte bei Beiträgen von ignorierten Nutzern eine kurze Zeile im Sinne von "Beitrag von xxx ausgeblendet weil du xxx ignorierst" auf. Das würde ich mir wieder wünschen.

MfG, Heiko

**Comment by theZiz** [comment]
Ist leider nicht vorgesehen im neuen Forum. Ignorieren ist jetzt konsequent. :grin:
